version: '3.3'
services:
  transip-ddns:
    image: mbchristoff/transip-ddns:apache-latest
    volumes:
      - ./transip_settings.py:/var/www/html/lib/transip_settings.py
      #- ./logs:/var/log
    ports:
      - "8080:80"
    environment:
      - DOMAINS=@.domain.tld,*.domain.tld,sub.domain.tld
      - REMOTEKEY=mysupersecurekey